// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postId"`
	ParentID  *string    `json:"parentId,omitempty"`
	Text      string     `json:"text"`
	CreatedAt string     `json:"createdAt"`
	Children  []*Comment `json:"children"`
}

type CreateCommentInput struct {
	PostID   string                     `json:"postId"`
	ParentID graphql.Omittable[*string] `json:"parentId,omitempty"`
	Text     string                     `json:"text"`
}

type CreatePostInput struct {
	Title           string                   `json:"title"`
	Content         string                   `json:"content"`
	CommentsEnabled graphql.Omittable[*bool] `json:"commentsEnabled,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	CreatedAt       string     `json:"createdAt"`
	CommentsEnabled bool       `json:"commentsEnabled"`
	Comments        []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
