// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/mocks.go
//

// Package mock_comment_service is a generated GoMock package.
package mock_comment_service

import (
	context "context"
	reflect "reflect"

	broker "github.com/4udiwe/commnets-feed/internal/broker"
	model "github.com/4udiwe/commnets-feed/internal/graph/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentRepository is a mock of CommentRepository interface.
type MockCommentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommentRepositoryMockRecorder
	isgomock struct{}
}

// MockCommentRepositoryMockRecorder is the mock recorder for MockCommentRepository.
type MockCommentRepositoryMockRecorder struct {
	mock *MockCommentRepository
}

// NewMockCommentRepository creates a new mock instance.
func NewMockCommentRepository(ctrl *gomock.Controller) *MockCommentRepository {
	mock := &MockCommentRepository{ctrl: ctrl}
	mock.recorder = &MockCommentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentRepository) EXPECT() *MockCommentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentRepository) Create(ctx context.Context, comment *model.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCommentRepositoryMockRecorder) Create(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentRepository)(nil).Create), ctx, comment)
}

// GetByID mocks base method.
func (m *MockCommentRepository) GetByID(ctx context.Context, id string) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommentRepository)(nil).GetByID), ctx, id)
}

// GetByPostID mocks base method.
func (m *MockCommentRepository) GetByPostID(ctx context.Context, postID string, limit, offset int) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPostID", ctx, postID, limit, offset)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPostID indicates an expected call of GetByPostID.
func (mr *MockCommentRepositoryMockRecorder) GetByPostID(ctx, postID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPostID", reflect.TypeOf((*MockCommentRepository)(nil).GetByPostID), ctx, postID, limit, offset)
}

// GetChildren mocks base method.
func (m *MockCommentRepository) GetChildren(ctx context.Context, parentID string, limit, offset int) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildren", ctx, parentID, limit, offset)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildren indicates an expected call of GetChildren.
func (mr *MockCommentRepositoryMockRecorder) GetChildren(ctx, parentID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildren", reflect.TypeOf((*MockCommentRepository)(nil).GetChildren), ctx, parentID, limit, offset)
}

// GetChildrenBatch mocks base method.
func (m *MockCommentRepository) GetChildrenBatch(ctx context.Context, parentIDs []string) (map[string][]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildrenBatch", ctx, parentIDs)
	ret0, _ := ret[0].(map[string][]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildrenBatch indicates an expected call of GetChildrenBatch.
func (mr *MockCommentRepositoryMockRecorder) GetChildrenBatch(ctx, parentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildrenBatch", reflect.TypeOf((*MockCommentRepository)(nil).GetChildrenBatch), ctx, parentIDs)
}

// GetCommentsByPostBatch mocks base method.
func (m *MockCommentRepository) GetCommentsByPostBatch(ctx context.Context, postIDs []string) (map[string][]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsByPostBatch", ctx, postIDs)
	ret0, _ := ret[0].(map[string][]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsByPostBatch indicates an expected call of GetCommentsByPostBatch.
func (mr *MockCommentRepositoryMockRecorder) GetCommentsByPostBatch(ctx, postIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsByPostBatch", reflect.TypeOf((*MockCommentRepository)(nil).GetCommentsByPostBatch), ctx, postIDs)
}

// MockPostRepository is a mock of PostRepository interface.
type MockPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepositoryMockRecorder
	isgomock struct{}
}

// MockPostRepositoryMockRecorder is the mock recorder for MockPostRepository.
type MockPostRepositoryMockRecorder struct {
	mock *MockPostRepository
}

// NewMockPostRepository creates a new mock instance.
func NewMockPostRepository(ctrl *gomock.Controller) *MockPostRepository {
	mock := &MockPostRepository{ctrl: ctrl}
	mock.recorder = &MockPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepository) EXPECT() *MockPostRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockPostRepository) GetByID(ctx context.Context, id string) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPostRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPostRepository)(nil).GetByID), ctx, id)
}

// MockCommentBroker is a mock of CommentBroker interface.
type MockCommentBroker struct {
	ctrl     *gomock.Controller
	recorder *MockCommentBrokerMockRecorder
	isgomock struct{}
}

// MockCommentBrokerMockRecorder is the mock recorder for MockCommentBroker.
type MockCommentBrokerMockRecorder struct {
	mock *MockCommentBroker
}

// NewMockCommentBroker creates a new mock instance.
func NewMockCommentBroker(ctrl *gomock.Controller) *MockCommentBroker {
	mock := &MockCommentBroker{ctrl: ctrl}
	mock.recorder = &MockCommentBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentBroker) EXPECT() *MockCommentBrokerMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockCommentBroker) Publish(postID string, comment *broker.Comment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", postID, comment)
}

// Publish indicates an expected call of Publish.
func (mr *MockCommentBrokerMockRecorder) Publish(postID, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockCommentBroker)(nil).Publish), postID, comment)
}

// Subscribe mocks base method.
func (m *MockCommentBroker) Subscribe(postID string) (<-chan *broker.Comment, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", postID)
	ret0, _ := ret[0].(<-chan *broker.Comment)
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockCommentBrokerMockRecorder) Subscribe(postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockCommentBroker)(nil).Subscribe), postID)
}
