package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/4udiwe/comments-feed/internal/graph/loaders"
	"github.com/4udiwe/comments-feed/internal/graph/model"
)

// Children is the resolver for the children field.
func (r *commentResolver) Children(ctx context.Context, obj *model.Comment, limit int32, offset int32) ([]*model.Comment, error) {
	loader := loaders.GetChildrenLoader(ctx)
	if loader == nil {
		return nil, fmt.Errorf("loader not found in context")
	}

	thunk := loader.Load(ctx, obj.ID)

	comments, err := thunk()
	if err != nil {
		return nil, err
	}

	return paginate(comments, int(limit), int(offset)), nil
	// // Вся логика батчевания и пагинации находится в сервисе
	// // Резолвер просто делегирует вызов
	// return r.CommentService.GetChildrenWithPagination(
	// 	ctx,
	// 	obj.ID,
	// 	int(limit),
	// 	int(offset),
	// )
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	return r.PostService.CreatePost(ctx, input)
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	return r.CommentService.CreateComment(ctx, input)
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, limit int32, offset int32) ([]*model.Comment, error) {

	loader := loaders.GetCommentsByPostLoader(ctx)
	if loader == nil {
		return nil, fmt.Errorf("loader not found in context")
	}

	thunk := loader.Load(ctx, obj.ID)

	comments, err := thunk()
	if err != nil {
		return nil, err
	}

	return paginate(comments, int(limit), int(offset)), nil

	// // Вся логика батчевания и пагинации находится в сервисе
	// // Резолвер просто делегирует вызов
	// return r.CommentService.GetCommentsByPostWithPagination(
	// 	ctx,
	// 	obj.ID,
	// 	int(limit),
	// 	int(offset),
	// )
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit int32, offset int32) ([]*model.Post, error) {
	return r.PostService.ListPosts(ctx, int(limit), int(offset))
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	return r.PostService.GetPost(ctx, id)
}

// CommentsByPost is the resolver for the commentsByPost field.
func (r *queryResolver) CommentsByPost(ctx context.Context, postID string, limit int32, offset int32) ([]*model.Comment, error) {
	return r.CommentService.GetCommentsByPost(ctx, postID, int(limit), int(offset))
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	return r.CommentService.SubscribeToComments(ctx, postID)
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
